import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { visibleCheckinSQL,viewerBindings } from "../../../lib/social-access";
export const dynamic="force-dynamic";
export async function GET(request:Request){
 const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in to continue."},{status:401});
 const db=env.DB;if(!db)return Response.json({error:"Database unavailable."},{status:503});
 const id=new URL(request.url).searchParams.get("id")||user.userId;
 const person=await db.prepare("SELECT id,name,avatar_key AS avatarKey,weekday_wake AS weekdayWake,weekend_wake AS weekendWake,weekday_bed AS weekdayBed,weekend_bed AS weekendBed FROM people WHERE id=?").bind(id).first<{id:string;name:string;avatarKey:string|null;weekdayWake:string;weekendWake:string;weekdayBed:string;weekendBed:string}>();
 if(!person)return Response.json({error:"Person not found."},{status:404});
 const own=id===user.userId;
 const goals=own?(await db.prepare(`SELECT g.id,g.circle_id AS circleId,g.kind,g.slot,COALESCE(e.title,g.title) AS title,COALESCE(e.cadence,g.cadence) AS cadence,g.target,COALESCE(e.weekly_day,g.weekly_day) AS weeklyDay,COALESCE(e.preferred_minutes,g.preferred_minutes) AS preferredMinutes,g.created_at AS createdAt,1 AS active FROM group_goals g JOIN members m ON m.circle_id=g.circle_id LEFT JOIN goal_choices c ON c.goal_id=g.id AND c.person_id=? LEFT JOIN personal_goal_edits e ON e.goal_id=g.id AND e.person_id=? WHERE m.person_id=? AND g.active=1 AND COALESCE(c.enabled,1)=1 UNION ALL SELECT id,NULL AS circleId,kind,slot,title,cadence,NULL AS target,weekly_day AS weeklyDay,preferred_minutes AS preferredMinutes,created_at AS createdAt,active FROM personal_goals WHERE person_id=? AND active=1`).bind(id,id,id,id).all()):
 (await db.prepare(`SELECT DISTINCT g.id,g.circle_id AS circleId,g.kind,g.slot,COALESCE(e.title,g.title) AS title,COALESCE(e.cadence,g.cadence) AS cadence,g.target,COALESCE(e.weekly_day,g.weekly_day) AS weeklyDay,COALESCE(e.preferred_minutes,g.preferred_minutes) AS preferredMinutes,g.created_at AS createdAt,1 AS active FROM group_goals g JOIN members actor ON actor.circle_id=g.circle_id AND actor.person_id=? LEFT JOIN goal_choices c ON c.goal_id=g.id AND c.person_id=? LEFT JOIN personal_goal_edits e ON e.goal_id=g.id AND e.person_id=? LEFT JOIN habit_visibility v ON v.person_id=? AND v.kind=g.kind AND v.slot=g.slot WHERE g.active=1 AND COALESCE(c.enabled,1)=1 AND (v.visibility='public' OR (COALESCE(v.visibility,'group')='group' AND EXISTS (SELECT 1 FROM members viewer WHERE viewer.circle_id=g.circle_id AND viewer.person_id=?))) UNION ALL SELECT pg.id,NULL AS circleId,pg.kind,pg.slot,pg.title,pg.cadence,NULL AS target,pg.weekly_day AS weeklyDay,pg.preferred_minutes AS preferredMinutes,pg.created_at AS createdAt,pg.active FROM personal_goals pg JOIN habit_visibility v ON v.person_id=pg.person_id AND v.kind=pg.kind AND v.slot=pg.slot AND v.visibility='public' WHERE pg.person_id=? AND pg.active=1`).bind(id,id,id,id,user.userId,id).all());
 const visibility=own?`${visibleCheckinSQL}`:`(${visibleCheckinSQL} OR EXISTS (SELECT 1 FROM personal_goals pg JOIN habit_visibility v ON v.person_id=pg.person_id AND v.kind=pg.kind AND v.slot=pg.slot AND v.visibility='public' WHERE pg.person_id=x.person_id AND pg.kind=x.kind AND pg.slot=x.slot AND pg.active=1))`;
 const entries=await db.prepare(`SELECT x.id,x.person_id AS personId,x.date,x.kind,x.slot,x.value,x.logged_time AS loggedTime,x.details,x.status,x.photo_key AS photoKey,x.created_at AS createdAt,x.updated_at AS updatedAt FROM checkins x WHERE x.person_id=? AND ${visibility} ORDER BY x.date DESC,x.updated_at DESC LIMIT 5000`).bind(id,...viewerBindings(user.userId)).all();
 const friends=(await db.prepare(`SELECT p.id,p.name,p.avatar_key AS avatarKey FROM friendships f JOIN people p ON p.id=CASE WHEN f.requester_id=? THEN f.recipient_id ELSE f.requester_id END WHERE f.status='accepted' AND (f.requester_id=? OR f.recipient_id=?) ORDER BY p.name LIMIT 100`).bind(id,id,id).all()).results;
 return Response.json({person:{id:person.id,name:person.name,avatarKey:person.avatarKey},goals:goals.results,entries:entries.results,friends});
}